version: '3.9'

services:
  web: 
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/patitas-perdidas
    ports:
      - 8000:8000 #maquinaHost:mv
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY='django-insecure-y2*tpgzgo*pq4^!7*q!_iv^7!rdkdd&_8gq)%9@=ji+i4of$$83'
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: 