# Generated by Django 4.1.3 on 2022-12-14 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "genero",
                    models.CharField(
                        choices=[("h", "Hembra"), ("m", "Macho")],
                        default="h",
                        max_length=255,
                    ),
                ),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tamanio",
                    models.CharField(
                        choices=[
                            ("pequenio", "Pequeño"),
                            ("mediano", "Mediano"),
                            ("grande", "Grande"),
                        ],
                        default="mediano",
                        max_length=255,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="img/")),
                (
                    "idUsrRegistro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuerpo", models.CharField(max_length=255)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="mascotas.mascota",
                    ),
                ),
            ],
        ),
    ]
