# Generated by Django 4.1.3 on 2022-11-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "genero",
                    models.CharField(
                        choices=[("h", "Hembra"), ("m", "Macho")],
                        default="h",
                        max_length=255,
                    ),
                ),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tamanio",
                    models.CharField(
                        choices=[
                            ("pequenio", "Pequeño"),
                            ("mediano", "Mediano"),
                            ("grande", "Grande"),
                        ],
                        default="mediano",
                        max_length=255,
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
